# @format

name: package_windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "14"
          distribution: "adopt"

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Copy
        run: copy build\libs\midi2musicxml*.jar windows_script\

      - uses: actions/upload-artifact@v3
        with:
          name: Package_${{ matrix.os }}
          path: windows_script
