name: package

on:
  push:
    branches:
      - master
      - 36

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: build/libs

