name: package_windows

on:
  push:
    branches:
      - master
      - hotfix/windows_readme

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Copy
        run: copy build\libs\midi2musicxml*.jar windows_script\


      # A installer needs WIX tool. I was not able to build with GitHub Actions...
      - uses: actions/upload-artifact@v1
        with:
          name: Package_${{ matrix.os }}
          path: windows_script